# Generated by Django 6.0.3 on 2026-03-06 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("longitude", models.FloatField()),
                ("latitude", models.FloatField()),
                ("country", models.CharField(max_length=30)),
            ],
            options={
                "unique_together": {("name", "country")},
            },
        ),
        migrations.CreateModel(
            name="Weather",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mintemp", models.FloatField()),
                ("maxtemp", models.FloatField()),
                ("avgtemp", models.FloatField()),
                ("humidity", models.FloatField()),
                ("wind_speed", models.FloatField()),
                ("precipitation", models.FloatField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_records",
                        to="weather.city",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("city", "date")},
            },
        ),
    ]
