# Generated by Django 6.0.3 on 2026-03-07 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("weather", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="weather",
            name="avgtemp",
        ),
        migrations.RemoveField(
            model_name="weather",
            name="humidity",
        ),
    ]
